spring:
  servlet:
    multipart:
      maxFileSize: 30MB
      maxRequestSize: 30MB

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  datasource:
    url: jdbc:mysql://localhost/igallery?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 쉿-비밀

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging:
  level:
    me.silvernine: DEBUG

file:
  img: C:\img\
  thumbnail: C:\thumbnail\